### ISSUE TITLE
Update feature does not work.

### ISSUE THREAD

**Issue by wazerstar** [rex706/SAM#162]
Took lib to record it, i rekon it was never properly fixed?

Here's a video me starting it up all the time saying there's an update clicking update and it it starts to show progress, then closes.

https://streamable.com/zdupls

My settings.ini

```
[System]
Version=1.5.1.0
[Settings]
AccountsPerRow=4
StartWithWindows=False
StartMinimized=False
MinimizeToTray=False
PasswordProtect=False
SleepTime=2
RememberPassword=True
ClearUserData=False
HideAddButton=False
CheckForUpdates=True
CloseOnLogin=True
ListView=False
SandboxMode=False
[AutoLog]
LoginRecentAccount=False
RecentAccountIndex=1
LoginSelectedAccount=False
SelectedAccountIndex=-1
InputMethod=SendMessage
HandleIME=False
IME_2FA_ONLY=False
[Parameters]
cafeapplaunch=False
clearbeta=False
console=False
login=False
forceservice=False
nocache=False
noverifyfiles=False
silent=False
single_core=True
tcp=False
tenfoot=False
customParameters=True
customParametersValue=-no-dwrite -vrdisable -no-shared-textures
dev=False
[Location]
WindowLeft=635
WindowTop=383
ListViewHeight=300
ListViewWidth=750
[Steam]
Path=d:/games/steam/
ApiKey=
AutoReloadEnabled=False
AutoReloadInterval=30
LastAutoReload=
[Customize]
ButtonSize=105
ButtonColor=#FFDDDDDD
ButtonFontSize=0
ButtonFontColor=#FF000000
ButtonBannerColor=#7F000000
ButtonBannerFontSize=0
ButtonBannerFontColor=#FFFFFFFF
Theme=BaseDark
Accent=Blue
HideBanIcons=False
[Columns]
NameColumnIndex=0
DescriptionColumnIndex=1
TimeoutColumnIndex=2
VacBansColumnIndex=3
GameBansColumnIndex=4
EcoBanColumnIndex=5
LastBanColumnIndex=6
```

**Comment by MichaelDavidGK** [comment]
@rex706 still the case in 1.5.2.0

**Comment by rex706** [comment]
@MichaelDavidGK I don't have an issue. what happens?

**Comment by MichaelDavidGK** [comment]
> @MichaelDavidGK I don't have an issue. what happens?

it gives you a prompt to download, it downloads it and it doesn't replace old file :(

**Comment by rex706** [comment]
@MichaelDavidGK does it download the new SAM executable to the same directory as the old one?

**Comment by wazerstar** [comment]
@rex706 This is what happens, nothing, just goes loop when you restart client


https://streamable.com/qms5h1

**Comment by rex706** [comment]
Alright I pushed a minor update to the updater. Try again and let me know if it helps. You will know you have the new updater by the version in the title bar.

**Comment by wazerstar** [comment]
> Alright I pushed a minor update to the updater. Try again and let me know if it helps. You will know you have the new updater by the version in the title bar.

Cannot update anything when using latest client?

Tested on older version and still does the same.

**Comment by wazerstar** [comment]
@rex706 

New video

https://streamable.com/abnvs2

**Comment by MichaelDavidGK** [comment]
> Alright I pushed a minor update to the updater. Try again and let me know if it helps. You will know you have the new updater by the version in the title bar.

1.1.0.6 for updater, still doesn't work, maybe it is not downloading, I assumed it was as my internet is over 1gbps

**Comment by rex706** [comment]
It looks like it's crashing before it can actually download anything in the recent clip @wazerstar posted. There are try/catch clauses everywhere in the updater, which makes it weird that there isn't any error popup at any point. Maybe there is an issue with reading the manifest URL from the launch arguments.

**Comment by rex706** [comment]
@wazerstar please test it out again when you get the chance, thanks!

**Comment by wazerstar** [comment]
if you compare the 2 versions, now you can actually see some github url in the updater txt which you could not before.

but still crashes

https://streamable.com/m494mf

**Comment by MichaelDavidGK** [comment]
@rex706 any update on this?

**Comment by rex706** [comment]
@MichaelDavidGK I've tried a couple different things, but it is tricky to troubleshoot since it is working as expected for me. The updater is fed a URL to the update manifest file, which is this: https://raw.githubusercontent.com/rex706/SAM/master/latest.txt

For some reason the updater appears to crash either before or during the read operation for the manifest file. I don't think it actually starts the download process before it crashes, but I could be wrong since it's hard to tell from the videos exactly when it fails.

**Comment by wazerstar** [comment]
> @MichaelDavidGK I've tried a couple different things, but it is tricky to troubleshoot since it is working as expected for me. The updater is fed a URL to the update manifest file, which is this: https://raw.githubusercontent.com/rex706/SAM/master/latest.txt
> 
> For some reason the updater appears to crash either before or during the read operation for the manifest file. I don't think it actually starts the download process before it crashes, but I could be wrong since it's hard to tell from the videos exactly when it fails.

add some debug so we can give log?

**Comment by wazerstar** [comment]
@rex706 I just tested on a brand new windows 10 installation, and a server running Windows 11, same thing happens, it crashes, and never gets the file updated.

**Comment by rex706** [comment]
I will test later today with a fresh windows install before pushing another update for SAM.

**Comment by rex706** [comment]
Made some changes to the Updater. I think the problem is that SAM is not closing in time before the updater attempts to delete the existing file. Please try it again and let me know @wazerstar

**Comment by wazerstar** [comment]
> Made some changes to the Updater. I think the problem is that SAM is not closing in time before the updater attempts to delete the existing file. Please try it again and let me know @wazerstar

Yes works now, but does not delete update, finally!

This has been an issue ever since update was introduced and we talked about this on discord ever since early start of the program :)

I don't know how it never would fail for you..


Congrats with this and thanks :)
